### ISSUE TITLE
Add/edit/remove API libs from the web

### ISSUE THREAD

**Issue by MattIPv4** [botblock/BotBlock.org#12]
# Website/API Suggestion

## Description

The API libraries page runs off of a database table that contains all the library information that is displayed. This should have a way on the website to be able to add, edit & remove API libraries without having to manually access the database to make the changes.

Auth restrictions on this page:
 - Moderators can add & edit
 - Admins can remove

## Why

No one likes having to manually edit a database to make changes to a website page, let's make this moderator friendly by having a page on the website for it.

**Comment by Andre601** [comment]
And maybe also have a sub-page/place here where the info is stored?
Like a `/libraries` folder containing yml files where people could PR updates to the information?

**Comment by MattIPv4** [comment]
This is stored in the database, not files. YAML files are only used for development seed data. If there are changes that need to be made, the best place to let us know would be the Discord server, or creating an issue here to request the change.

**Comment by GavynStanley** [comment]
Is there an updated seed for the libraries table, or is the one in the repo the latest?

**Comment by MattIPv4** [comment]
The seed data in the repo is pretty old but should still work just fine to development :)

**Comment by GavynStanley** [comment]
My bad, I'm meaning the columns in the table, looking at other aspects of the site, there seems to be other columns that aren't included

**Comment by GavynStanley** [comment]
Cause I really have no way to look at columns in the tables rather than the migration files, which look to be old

**Comment by MattIPv4** [comment]
Request logging + kv cache have been added since the last seed export, but neither need or expect seed data.

**Comment by A-Trash-Coder** [comment]
Alright, thanks. Since it has been a year, are there any more specifics/requests you want for this specific issue?

**Comment by GavynStanley** [comment]
https://github.com/botblock/BotBlock.org/pull/81
