### ISSUE TITLE
Ratelimit on /api/count returns wrong bot ID in production

### ISSUE THREAD

**Issue by MattIPv4** [botblock/BotBlock.org#16]
# Bug Report

## Description 

This bug is only reproducible in the production test suite.

When making multiple valid requests in quick succession to the /api/count endpoint, the ratelimit response is returned as expected.

However, the bot id contained within that response does not match the bot id the request was sent as.

I really have no idea where this failure is coming from, it might be the app itself, but I would expect to then be able to reproduce this in staging or development -- perhaps its related to the load on the site. This could also be some form of caching issue, though Cloudflare is set to never cache API requests and IIS should not be caching anything at all.

## Steps to reproduce

1. Be a moderator logged into the production site
2. Run the test suite at /test
3. Observe test failure

<img width="1105" alt="image" src="https://user-images.githubusercontent.com/12371363/66271827-7c341700-e85a-11e9-9ad7-c4ab3a3518dc.png">

## Expected behavior

The ratelimit response should have the correct bot id.

## Logs or Screenshots

See above.

**Comment by MattIPv4** [comment]
Update to this, @advaith1 has reproduced this by simply using the API, receiving a ratelimit response with an incorrect bot id and the ratelimit not applying correctly (lasted over 10 mins).

**Comment by MattIPv4** [comment]
After the production deployment today, this test is no longer failing in the production test suite, even after running the test suite multiple times.

As such, I am going to close this issue for now. If this failure resurfaces, we can open this issue again and take a closer look at what's going on.

**Comment by jacobmitchell04** [comment]
After running a test in production today, the issue has now returned. The issue has been re-opened.
