### ISSUE TITLE
Add eslint to the test suite

### ISSUE THREAD

**Issue by MattIPv4** [botblock/BotBlock.org#21]
# Website/API Suggestion

## Description

We should add eslint to the test suite with a full rule set based off of the existing code style of the project (pretty standard). If there exists an eslint plugin for pug, we should also make use of that.

## Why

Consistent code style.

**Comment by VivekSingh777** [comment]
Can i work on this @MattIPv4 ?

**Comment by MattIPv4** [comment]
Sure thing, absolutely @VivekSingh777

**Comment by MattIPv4** [comment]
Config & test added in https://github.com/botblock/BotBlock.org/pull/25
Fixing existing errors in https://github.com/botblock/BotBlock.org/pull/26

Can then merge `eslint` into `node`.
