### ISSUE TITLE
Add best practices page

### ISSUE THREAD

**Issue by Andre601** [botblock/BotBlock.org#58]
# Website/API Suggestion

## Description
The website should have the content from https://github.com/botblock/discord-botlist-best-practices as a sub-page available, to find it easier.

## Why
It looks and feels better to have the content of the readme as a page instead of it being a readme on a GitHub repo that barely someone looks at.

**Comment by MattIPv4** [comment]
From a technical aspect, I think something like this would be a good way to implement it:

 - Create a new app task that fetches & stores the contents of the best practices locally (the single md file, can be stored in the db or memory)
   - This task should run whenever the app starts up
 - Create a page that simply renders the cached data
   - The app already has MD rendering logic for the about page, use that here

**Comment by Andre601** [comment]
Why did you add the hacktoberfest label @MattIPv4? xD

**Comment by MattIPv4** [comment]
So I wouldn't forget in October if no one had done this by then

**Comment by MattIPv4** [comment]
Added in https://github.com/botblock/BotBlock.org/pull/65
