### ISSUE TITLE
Add descriptions to List Features

### ISSUE THREAD

**Issue by Andre601** [botblock/BotBlock.org#68]
# Website/API Suggestion

## Description
The listed features in the JSON array `features` (In `GET /api/lists`) seems to have a description filed, which contains null values for every feature.
I assume this is for future use of having a description about the specific feature (What makes it positive/negative perhaps)?

If that's the case would I give some ideas for possible descriptions.
- `Has Ads on Site`
Site displays advertisement.
- `Offers Paid Promotion`
Site offers a way to promote a bot through payment (e.g. paid slots on frontpage).
- `Paid Access`
You have to pay in order to gain access to the site and its API.
- `HTML Long Description`
Site supports HTML in the bot's long description.
- `Has internationalisation Support`
Site supports adding descriptions of a bot in multiple languages.
- `Iframe Long Description`
Site supports iframes in the bot's long description.
- `Markdown Long Description`
Site supports Markdown in the bot's long description.
- `Certified Bot Vanity URLs`
Site offers vanity URLs for certified bots.
- `Custom Bot Donate Link`
Site has an option to add a custom donation link for the bot.
- `Custom Bot GitHub Link`
Site has an option to add a custom GitHub link to the bot.
- `Custom Bot Invite Link`
Site has an option to add a custom invite link for the bot.
- `Custom Bot Support Link`
Site has an option to add a custom support link for the bot.
- `Custom Bot Website Link`
Site has an option to add a custom website link for the bot.
- `Discord Bot Support Link`
Site has an option to add a discord support link.
- `Vanity URLs for all`
Site offers a vanity URL for bots.
- `Has Voting`
Site offers a way to vote for a bot.
- `Votes sent to Webhooks`
Site sends votes through Webhooks.
- `Voting Data Exposed`
Site allows others to lookup vote data of a bot (e.g. through an API endpoint).
- `Additional Bot Owners/Editors`
Site allows to add additional Bot Owners/Editors to the bot.
- `Has Categories or Tags`
Site offers categories or tags that can be added to a bot.
- `Has Certification Programm`
Site has an option to get a bot certified.
- `Has Mobile Support`
Site is mobile friendly (Can be used on smartphones/tablets).
- `Has Search`
Site offers a way to search for bots on it.
- `Has Widget`
Site offers a widget (Image depicting specific stats of the bot).
- `Requires Owner in Server`
Site requires the Bot Owner to be in its Discord Server.
- `Server Count API`
Site offers an API to post the server count of a bot.

## Why
Some of the Features can sound confusing or may sound similar. For example, what is the exact difference between `Custom Bot Support Link` and `Discord Bot Support Link`?
So a description that might be shown when hovering over it would be a good option imo.

**Comment by jacobmitchell04** [comment]
Descriptions have been implemented.
