### ISSUE TITLE
Consolidate list adding/editing code

### ISSUE THREAD

**Issue by MattIPv4** [botblock/BotBlock.org#7]
# Website/API Suggestion

## Description

The code that is used on the post routes for adding a new list and editing an existing list is almost identical and it this should be consolidated down to a single set of code that bot routes can call to.

Adding: src/Routes/Lists.js#L226-L269
Editing: src/Routes/Lists.js#L321-L393

## Why

Code duplication is a pain to deal with and keep track of. If we added new bits to the list model, both routes may need to be updated etc.

**Comment by jacobmitchell04** [comment]
Code has been consolidated #57
