### ISSUE TITLE
Breadcrumbs using encoded URI

### ISSUE THREAD

**Issue by GavynStanley** [botblock/BotBlock.org#71]
# Bug Report

## Description

Whenever you search for a bot list, at the bottom of the page on the 'footer' it shows the search term with '%20' in between the words

## Steps to reproduce

Search for a bot list, scroll to the bottom

## Expected behavior

Display the name of the bot list normally

## Logs or Screenshots

![https://gyazo.com/44e7d6914d0f670d8d32c9c20b311718](https://i.gyazo.com/44e7d6914d0f670d8d32c9c20b311718.png)

**Comment by MattIPv4** [comment]
#78
