### ISSUE TITLE
What host to use for this?

### ISSUE THREAD

**Issue by CrypticKingJoe** [botblock/BotBlock.org#77]
Sorry if wrong topic but I currently have namecheap, willing to get another for this
does anyone have a quick rundown on how to set this up?

**Comment by MattIPv4** [comment]
👋 This is hosted on DigitalOcean. It needs Node.js 10 installed (as noted in README.md), as well as a MySQL database being available.

**Comment by MattIPv4** [comment]
No further progress, closing

**Comment by Randomx24** [comment]
> No further progress, closing

can you use replit or heroku or glitch or?
