### ISSUE TITLE
Shard count is supported but is not being sent to the bot list

### ISSUE THREAD

**Issue by cheesycod** [botblock/BotBlock.org#83]
# Bug Report

## Steps to reproduce

(This is with a test api token)

python3
import requests
a = requests.post(“https://botblock.org/api/count”, json = {“server_count”: 1414, “shard_count”: 1253, “bot_id”: “ 631115725876101150”, “fateslist.xyz”: “ MYKRbUWNi09bTk4OBdQgPTYBQaT2NnJu57tt0Sto1zdUEKb2Uf31LFPp0ImoKnSbvhiwt2SgRjGW2noiPsiUB8YwOVk8DavWrZDgTHBFwsKZpQfKjCfb6nppF32GgLVcc204“)
a = a,json()
a

## Expected behavior

guild and shard count should be sent to the list as fates list does support shard count: https://botblock.org/lists/fateslist.xyz but only the guild count is actually sent which is odd. 
## Logs or Screenshots

![](https://cdn.discordapp.com/attachments/536585380389191720/812406383386427442/image0.png)

![](https://cdn.discordapp.com/attachments/536585380389191720/812407031302324274/image0.png)

**Comment by MattIPv4** [comment]
https://github.com/botblock/BotBlock.org/commit/9502a8d0fb04b063ececec687ba3e666b2092dea
