### ISSUE TITLE
[Libraries] Download for JavaBotBlockAPI updated

### ISSUE THREAD

**Issue by Andre601** [botblock/BotBlock.org#85]
# Website/API Suggestion

## Description
The download location/link for JavaBotBlockAPI has been updated due to Bintray shutting down ("sundowning" in their words) in may this year.

Downloads are now provided through the nexus server of ci.codemc.io (Which was already used to host Dev Builds of the lib)

The latest release is the exact same as the latest dev build on the CI, so a direct link to the latest successful build on the CI should be sufficient enough for the "View on \<page>" button:
https://ci.codemc.io/job/botblock/job/JavaBotBlockAPI/lastSuccessfulBuild/

For getting the latest version to display would you need to use the nexus badge type of shields.io:
https://img.shields.io/nexus/maven-public/org.botblock/javabotblockapi-core?label=CodeMC&server=https%3A%2F%2Frepo.codemc.io&style=flat-square

Result:
![badge](https://img.shields.io/nexus/maven-public/org.botblock/javabotblockapi-core?label=CodeMC&server=https%3A%2F%2Frepo.codemc.io&style=flat-square)

## Why
The download links won't work anymore once bintray sundowned so an update should be made.

----
EDIT:
I also noticed that the YAML file used for storing info of libs (from the db iirc) seems to be outdated and no longer represents the latest iteration of the description found on botblock.org
This should perhaps also be updated.

**Comment by jacobmitchell04** [comment]
This has been updated.
