### ISSUE TITLE
Config flag to send Discord notifications

### ISSUE THREAD

**Issue by MattIPv4** [botblock/BotBlock.org#9]
# Website/API Suggestion

## Description

Currently, if you edit a website on the staging deployment or the scheduled tasks update an icon on staging, this will still send a message to the Discord channel. We should add a boolean flag to the config file that disables the notifications to Discord so that staging can have them disabled.

## Why

Discord messages from staging are annoying and confusing for people in the Discord guild.

**Comment by stijnvdkolk** [comment]
Maybe I have time to look into this, not sure tho
